"""
Cron job: fetch new PubMed papers every 12 hours, tag via Claude Batch API.

Two-part flow per run:
  Part A — fetch papers published in the last 48 h, submit a Claude batch job.
  Part B — retrieve any previously submitted batch that has finished,
            normalize tags (using the tag_mappings table + a lightweight pass-2
            Claude call for any unknown raw tags), and ingest papers into the DB.

Run via:
    python -m app.cron_ingest

Expected env vars:
    DATABASE_URL         — same as the web app (Railway injects this automatically)
    ANTHROPIC_API_KEY    — for Claude Batch API calls
    NCBI_EMAIL           — required by NCBI Entrez ToS
    NCBI_API_KEY         — optional, raises rate limit from 3 to 10 req/s
"""

import json
import logging
import os
import time
from datetime import datetime, timezone
from typing import Optional

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Claude tagging prompt (numeric confidence 0–10)
# ---------------------------------------------------------------------------

TAGGING_SYSTEM = """You are a scientific tagger for a biomedical literature database.
Your tags will be used to build a searchable taxonomy.
Respond with JSON only."""

TAGGING_PROMPT = """Tag this paper with 3–5 single-word tags.

SPECIFICITY RULES:
- Too generic (FORBIDDEN): genomics, biology, science, research, analysis, study
- Too specific (AVOID): species names, geographic locations, software names, single gene names
- Good tags: METHOD level (metagenomics, transcriptomics, proteomics, sequencing)
- Good tags: BIOLOGICAL CONCEPT level (microbiome, AMR, biofilm, virulence, immunity)
- Good tags: DISEASE/CONDITION level (tuberculosis, sepsis, colitis, cancer, infection)
- Prefer terms specific enough to exclude 80%+ of papers but general enough for dozens/year

For each tag provide a confidence score from 0 (low) to 10 (high).

Respond with JSON only:
{{"tags": [{{"tag": "metagenomics", "confidence": 8}}, ...]}}

Title: {title}
Abstract: {abstract}"""

CONSISTENCY_SYSTEM = """You are a taxonomy curator for a biomedical literature database.
Respond with JSON only."""

CONSISTENCY_PROMPT = """Normalize these raw tags generated by an AI tagger.
Map each to the closest existing clean tag, or to a normalized version of itself.

Rules:
1. Map to an existing clean tag if the raw tag is a synonym or variant
2. Standardize to lowercase; prefer single-word or hyphenated forms
3. Return null only for tags that are clearly too generic or too specific
4. If a raw tag is already fine, map it to itself

Existing clean tags already in the system:
{known_tags}

Raw tags to normalize (each on one line):
{raw_tags}

Respond with JSON only:
{{"mapping": {{"raw_tag": "clean_tag_or_null", ...}}}}"""


# ---------------------------------------------------------------------------
# PubMed helpers (adapted from private_local/tagger/pubmed_abstract.py)
# ---------------------------------------------------------------------------

def _setup_entrez():
    from Bio import Entrez
    Entrez.email = os.environ.get("NCBI_EMAIL", "rnews@example.com")
    api_key = os.environ.get("NCBI_API_KEY")
    if api_key:
        Entrez.api_key = api_key
    return Entrez


def fetch_pubmed_papers(lookback_days: int = 2) -> list[dict]:
    """Fetch papers from journals.json published in the last `lookback_days` days."""
    from pathlib import Path
    import json as _json

    journals_path = Path(__file__).parent.parent / "journals.json"
    journals = _json.loads(journals_path.read_text())

    Entrez = _setup_entrez()
    all_papers: list[dict] = []
    seen_pmids: set[str] = set()

    for journal in journals:
        pubmed_name = journal["pubmed"]
        display_name = journal["name"]

        query = f'"{pubmed_name}"[Journal] AND hasabstract NOT preprint[pt]'
        try:
            handle = Entrez.esearch(
                db="pubmed", term=query,
                reldate=lookback_days, datetype="edat",
                retmax=500,
            )
            record = Entrez.read(handle)
            handle.close()
        except Exception as e:
            log.warning(f"PubMed search failed for {pubmed_name}: {e}")
            continue

        pmids = record.get("IdList", [])
        if not pmids:
            time.sleep(0.4)
            continue

        # Fetch full records in batches
        try:
            for i in range(0, len(pmids), 200):
                batch = pmids[i:i + 200]
                handle = Entrez.efetch(
                    db="pubmed", id=",".join(batch),
                    rettype="medline", retmode="text",
                )
                from Bio import Medline
                for rec in Medline.parse(handle):
                    parsed = _parse_medline_record(rec, display_name)
                    if parsed and parsed["pmid"] not in seen_pmids:
                        all_papers.append(parsed)
                        seen_pmids.add(parsed["pmid"])
                handle.close()
                time.sleep(0.4)
        except Exception as e:
            log.warning(f"PubMed fetch failed for {pubmed_name}: {e}")

        time.sleep(0.6)

    log.info(f"PubMed: found {len(all_papers)} papers across {len(journals)} journals")
    return all_papers


def _parse_medline_record(rec: dict, journal_display: str) -> Optional[dict]:
    pmid = rec.get("PMID", "")
    abstract = rec.get("AB", "").strip()
    if not abstract:
        return None
    pub_types = rec.get("PT", [])
    if any("preprint" in pt.lower() for pt in pub_types):
        return None

    doi = ""
    for aid in rec.get("AID", []):
        if "[doi]" in aid:
            doi = aid.replace(" [doi]", "").strip()
            break

    return {
        "pmid": pmid,
        "doi": doi,
        "title": rec.get("TI", "").strip(),
        "abstract": abstract,
        "journal": journal_display,
        "journal_abbr": rec.get("TA", ""),
        "pub_date": rec.get("DP", ""),
        "epub_date": rec.get("DEP", ""),
        "authors": rec.get("AU", []),
        "pub_types": pub_types,
    }


# ---------------------------------------------------------------------------
# Deduplication
# ---------------------------------------------------------------------------

def _build_existing_sets(db) -> tuple[set, set, set]:
    """Return (ingested_urls, ingested_display_urls, pending_pmids).

    pending_pmids covers papers already in a batch that hasn't been retrieved
    yet — avoids re-submitting the same paper across overlapping 48 h windows.
    """
    from app.models import Item, IngestBatch, IngestPendingPaper
    urls = {r[0] for r in db.query(Item.url).filter(Item.url.isnot(None)).all()}
    display = {r[0] for r in db.query(Item.display_url).filter(Item.display_url.isnot(None)).all()}
    pending_pmids = {
        r[0]
        for r in (
            db.query(IngestPendingPaper.pmid)
            .join(IngestBatch)
            .filter(IngestBatch.status == "pending")
            .all()
        )
    }
    return urls, display, pending_pmids


def _is_duplicate(paper: dict, existing_urls: set, existing_display: set,
                  pending_pmids: set) -> bool:
    from app.ingest_utils import normalize_doi_url
    if paper.get("pmid") in pending_pmids:
        return True
    doi_url = normalize_doi_url(paper.get("doi", ""))
    return doi_url in existing_urls or doi_url in existing_display


# ---------------------------------------------------------------------------
# Part A — fetch & submit batch
# ---------------------------------------------------------------------------

def _run_part_a(db) -> dict:
    stats = {"found": 0, "skipped_dup": 0, "sent": 0, "batch_id": None}

    papers = fetch_pubmed_papers(lookback_days=2)
    stats["found"] = len(papers)

    if not papers:
        return stats

    existing_urls, existing_display, pending_pmids = _build_existing_sets(db)
    new_papers = [p for p in papers if not _is_duplicate(p, existing_urls, existing_display, pending_pmids)]
    stats["skipped_dup"] = len(papers) - len(new_papers)

    # Only papers with sufficient abstracts can be tagged
    new_papers = [p for p in new_papers if len(p.get("abstract", "")) >= 100]

    if not new_papers:
        log.info("Part A: no new papers to submit")
        return stats

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        log.error("ANTHROPIC_API_KEY not set — skipping batch submission")
        return stats

    import anthropic as _anthropic
    client = _anthropic.Anthropic(api_key=api_key)

    requests = []
    for paper in new_papers:
        requests.append({
            "custom_id": paper["pmid"],
            "params": {
                "model": "claude-haiku-4-5-20251001",
                "max_tokens": 256,
                "system": TAGGING_SYSTEM,
                "messages": [{
                    "role": "user",
                    "content": TAGGING_PROMPT.format(
                        title=paper["title"],
                        abstract=paper["abstract"][:1400],
                    ),
                }],
            },
        })

    log.info(f"Part A: submitting batch of {len(requests)} papers")
    batch = client.messages.batches.create(requests=requests)
    log.info(f"Part A: batch submitted — {batch.id}")

    from app.models import IngestBatch, IngestPendingPaper
    ingest_batch = IngestBatch(
        claude_batch_id=batch.id,
        submitted_at=datetime.now(timezone.utc).replace(tzinfo=None),
        n_submitted=len(new_papers),
        status="pending",
    )
    db.add(ingest_batch)
    db.flush()

    for paper in new_papers:
        db.add(IngestPendingPaper(
            batch_id=ingest_batch.id,
            pmid=paper["pmid"],
            paper_json=json.dumps(paper),
            abstract=paper.get("abstract", ""),
        ))
    db.flush()

    stats["sent"] = len(new_papers)
    stats["batch_id"] = batch.id
    return stats


# ---------------------------------------------------------------------------
# Pass-2 helpers (tag normalisation)
# ---------------------------------------------------------------------------

def _load_mapping(db, raw_tags: set[str]) -> tuple[dict, set]:
    """Return (known_mappings, unknown_raw_tags) from the tag_mappings table."""
    from app.models import TagMapping
    known: dict[str, Optional[str]] = {}
    unknown: set[str] = set()
    for raw in raw_tags:
        row = db.query(TagMapping).filter(TagMapping.raw_tag == raw).first()
        if row:
            known[raw] = row.clean_tag
        else:
            unknown.add(raw)
    return known, unknown


def _run_pass2(client, db, unknown_raw_tags: set[str]) -> dict[str, Optional[str]]:
    """Ask Claude Sonnet to normalize unknown raw tags. Updates tag_mappings table."""
    from app.models import Tag, TagMapping

    known_clean = sorted({r[0] for r in db.query(Tag.name).all()})
    known_tags_str = ", ".join(known_clean[:300])  # cap to avoid giant prompts
    raw_tags_str = "\n".join(sorted(unknown_raw_tags))

    log.info(f"Pass-2: normalizing {len(unknown_raw_tags)} unknown raw tags via Sonnet")

    try:
        response = client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=2048,
            system=CONSISTENCY_SYSTEM,
            messages=[{
                "role": "user",
                "content": CONSISTENCY_PROMPT.format(
                    known_tags=known_tags_str,
                    raw_tags=raw_tags_str,
                ),
            }],
        )
        text = response.content[0].text.strip().replace("```json", "").replace("```", "").strip()
        result = json.loads(text)
        mapping = result.get("mapping", {})
    except Exception as e:
        log.warning(f"Pass-2 Claude call failed: {e} — keeping raw tags as-is")
        mapping = {}

    # Merge: unknowns not in the response default to keeping the raw tag
    now = datetime.now(timezone.utc).replace(tzinfo=None)
    final: dict[str, Optional[str]] = {}
    for raw in unknown_raw_tags:
        clean = mapping.get(raw, raw)  # default: keep raw
        final[raw] = clean
        db.merge(TagMapping(raw_tag=raw, clean_tag=clean, updated_at=now))
    db.flush()

    return final


# ---------------------------------------------------------------------------
# Part B — retrieve completed batches & ingest
# ---------------------------------------------------------------------------

def _run_part_b(db) -> dict:
    stats = {
        "checked": 0,
        "retrieved": 0,
        "new_tags": 0,
        "added": 0,
        "discarded_user": 0,
    }

    from app.models import IngestBatch, IngestPendingPaper, Item, ItemTag, ItemAbstract

    pending_batches = db.query(IngestBatch).filter(IngestBatch.status == "pending").all()
    stats["checked"] = len(pending_batches)

    if not pending_batches:
        log.info("Part B: no pending batches")
        return stats

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        log.error("ANTHROPIC_API_KEY not set — skipping batch retrieval")
        return stats

    import anthropic as _anthropic
    client = _anthropic.Anthropic(api_key=api_key)

    from app.database import get_or_create_bot_user
    from app.ingest_utils import normalize_doi_url, get_or_create_tag, best_pub_date, JOURNAL_INDEX, tag_vote_count

    bot_id = get_or_create_bot_user()

    for batch_row in pending_batches:
        log.info(f"Part B: checking batch {batch_row.claude_batch_id}")

        try:
            batch_info = client.messages.batches.retrieve(batch_row.claude_batch_id)
        except Exception as e:
            log.warning(f"Failed to retrieve batch info: {e}")
            continue

        if batch_info.processing_status != "ended":
            log.info(f"  → not ready yet ({batch_info.processing_status})")
            continue

        # Collect raw tags per PMID from batch results
        pending_papers = {
            p.pmid: p
            for p in db.query(IngestPendingPaper)
            .filter(IngestPendingPaper.batch_id == batch_row.id)
            .all()
        }
        paper_raw_tags: dict[str, list[dict]] = {}

        for result in client.messages.batches.results(batch_row.claude_batch_id):
            pmid = result.custom_id
            if result.result.type != "succeeded":
                continue
            try:
                text = (result.result.message.content[0].text
                        .strip().replace("```json", "").replace("```", "").strip())
                parsed = json.loads(text)
                tags = parsed.get("tags", [])
                if tags:
                    paper_raw_tags[pmid] = tags
            except (json.JSONDecodeError, IndexError):
                continue

        # Collect all raw tag strings and look them up in tag_mappings
        all_raw = {t["tag"].lower().strip() for tags in paper_raw_tags.values() for t in tags}
        known_mappings, unknown = _load_mapping(db, all_raw)

        if unknown:
            new_mappings = _run_pass2(client, db, unknown)
            known_mappings.update(new_mappings)
            stats["new_tags"] += len(unknown)

        # Build current dedup sets (re-query to catch papers ingested since part A ran).
        # pending_pmids not needed here — we're processing papers from the batch itself.
        existing_urls, existing_display, _ = _build_existing_sets(db)

        for pmid, raw_tags in paper_raw_tags.items():
            pending = pending_papers.get(pmid)
            if not pending:
                continue

            paper = json.loads(pending.paper_json)
            doi_url = normalize_doi_url(paper.get("doi", ""))

            if doi_url in existing_urls or doi_url in existing_display:
                stats["discarded_user"] += 1
                log.info(f"  DUP (user): {paper.get('title', pmid)[:60]}")
                continue

            # Apply tag mapping
            final_tags: list[dict] = []
            seen_names: set[str] = set()
            for t in raw_tags:
                raw = t["tag"].lower().strip()
                clean = known_mappings.get(raw, raw)
                if clean is None or clean in seen_names:
                    continue
                final_tags.append({"tag": clean, "confidence": t.get("confidence", 5)})
                seen_names.add(clean)

            if not final_tags:
                continue

            # Determine publication date
            pub_date_obj = best_pub_date(paper)
            if pub_date_obj:
                created_at = datetime(pub_date_obj.year, pub_date_obj.month, pub_date_obj.day)
                pub_date_str = pub_date_obj.strftime("%Y-%m-%d")
            else:
                created_at = datetime.now(timezone.utc).replace(tzinfo=None)
                pub_date_str = paper.get("pub_date", "")

            authors = paper.get("authors", [])
            journal_display = JOURNAL_INDEX.get(paper["journal"].lower(), paper["journal"])

            item = Item(
                url=doi_url,
                title=paper["title"],
                item_type="paper",
                journal=journal_display,
                first_author=authors[0] if authors else None,
                last_author=authors[-1] if len(authors) > 1 else None,
                publication_date=pub_date_str,
                doi=doi_url,
                submitter_id=bot_id,
                created_at=created_at,
                auto_ingested=True,
            )
            for td in final_tags[:5]:
                item.item_tags.append(
                    ItemTag(
                        tag=get_or_create_tag(db, td["tag"]),
                        vote_count=tag_vote_count(td),
                    )
                )
            db.add(item)
            db.flush()

            db.add(ItemAbstract(item_id=item.id, abstract=pending.abstract))

            existing_urls.add(doi_url)
            stats["retrieved"] += 1
            stats["added"] += 1

        # Mark batch as retrieved and clean up pending paper rows
        batch_row.status = "retrieved"
        batch_row.retrieved_at = datetime.now(timezone.utc).replace(tzinfo=None)
        db.query(IngestPendingPaper).filter(
            IngestPendingPaper.batch_id == batch_row.id
        ).delete(synchronize_session=False)
        db.flush()
        log.info(f"  → batch {batch_row.claude_batch_id} processed ({stats['added']} papers added so far)")

    db.commit()
    return stats


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def run_cron():
    from app.database import init_db, SessionLocal
    from app.models import IngestReport

    init_db()
    db = SessionLocal()

    report_data: dict = {
        "papers_found": 0,
        "papers_skipped_dup": 0,
        "papers_sent": 0,
        "claude_batch_submitted": None,
        "batches_checked": 0,
        "papers_retrieved": 0,
        "new_tags": 0,
        "papers_added": 0,
        "papers_discarded_user_submitted": 0,
        "notes": None,
    }

    try:
        log.info("=== Cron run starting ===")

        # Part B first: ingest completed batches from previous runs
        b = _run_part_b(db)
        report_data["batches_checked"] = b["checked"]
        report_data["papers_retrieved"] = b["retrieved"]
        report_data["new_tags"] = b["new_tags"]
        report_data["papers_added"] = b["added"]
        report_data["papers_discarded_user_submitted"] = b["discarded_user"]

        # Part A: fetch new papers and submit a fresh batch
        a = _run_part_a(db)
        report_data["papers_found"] = a["found"]
        report_data["papers_skipped_dup"] = a["skipped_dup"]
        report_data["papers_sent"] = a["sent"]
        report_data["claude_batch_submitted"] = a.get("batch_id")

        log.info(
            f"=== Cron complete — "
            f"found={a['found']} sent={a['sent']} "
            f"added={b['added']} discarded={b['discarded_user']} ==="
        )

    except Exception as e:
        log.exception("Cron run failed")
        report_data["notes"] = str(e)

    finally:
        report = IngestReport(
            run_at=datetime.now(timezone.utc).replace(tzinfo=None),
            **report_data,
        )
        db.add(report)
        try:
            db.commit()
        except Exception:
            db.rollback()
        db.close()


if __name__ == "__main__":
    run_cron()
